# This is a basic workflow to help you get started with Actions
on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az group list
        curl https://raw.githubusercontent.com/cape-sh/cape-azure/master/azuredeploy.json > azuredeploy.json
        curl https://raw.githubusercontent.com/cape-sh/cape-azure/master/azuredeploy.parameters.json > azuredeploy.parameters.json
        templateFile=azuredeploy.json
        parameterFile=azuredeploy.parameters.json
        az deployment group create   --name capesaasdeployment   --resource-group cape   --template-file $templateFile --parameters
